# Generated by Django 2.0.2 on 2020-03-14 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relation',
            name='person',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Relation',
        ),
    ]
