# Generated by Django 2.0.2 on 2020-03-14 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree', '0003_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relatonship', to='family_tree.Person'),
        ),
    ]
