# Generated by Django 2.0.2 on 2020-03-13 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rp',
            fields=[
                ('room_no', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('team', models.CharField(choices=[('B', 'Blue Team'), ('O', 'Orange Team'), ('G', 'Green Team')], default='B', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='rp',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rp', to='ammudu.Student'),
        ),
    ]
