# Generated by Django 2.0.2 on 2020-03-12 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='act', to='imdb.Actor'),
        ),
        migrations.AlterField(
            model_name='cast',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='move', to='imdb.Movie'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='movies', through='imdb.Cast', to='imdb.Actor'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dir', to='imdb.Director'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='movie_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mov', to='imdb.Movie'),
        ),
    ]
