# Generated by Django 2.0.2 on 2020-03-12 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0002_auto_20200312_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='director_name',
            new_name='director',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='movie_id',
            new_name='movie',
        ),
    ]
