# Generated by Django 2.0.2 on 2020-03-13 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0003_auto_20200312_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='movie',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='mov', to='imdb.Movie'),
        ),
    ]
